# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /cvmfs/sft.cern.ch/lcg/releases/CMake/3.11.1-daf3a/x86_64-slc6-gcc62-opt/bin/cmake

# The command to remove a file.
RM = /cvmfs/sft.cern.ch/lcg/releases/CMake/3.11.1-daf3a/x86_64-slc6-gcc62-opt/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/users/yihuilai/crystal_bar

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/users/yihuilai/crystal_bar

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/cvmfs/sft.cern.ch/lcg/releases/CMake/3.11.1-daf3a/x86_64-slc6-gcc62-opt/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/cvmfs/sft.cern.ch/lcg/releases/CMake/3.11.1-daf3a/x86_64-slc6-gcc62-opt/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/cvmfs/sft.cern.ch/lcg/releases/CMake/3.11.1-daf3a/x86_64-slc6-gcc62-opt/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/cvmfs/sft.cern.ch/lcg/releases/CMake/3.11.1-daf3a/x86_64-slc6-gcc62-opt/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/cvmfs/sft.cern.ch/lcg/releases/CMake/3.11.1-daf3a/x86_64-slc6-gcc62-opt/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/cvmfs/sft.cern.ch/lcg/releases/CMake/3.11.1-daf3a/x86_64-slc6-gcc62-opt/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/cvmfs/sft.cern.ch/lcg/releases/CMake/3.11.1-daf3a/x86_64-slc6-gcc62-opt/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/cvmfs/sft.cern.ch/lcg/releases/CMake/3.11.1-daf3a/x86_64-slc6-gcc62-opt/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/users/yihuilai/crystal_bar/CMakeFiles /data/users/yihuilai/crystal_bar/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/users/yihuilai/crystal_bar/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CEPC_CaloTiming

# Build rule for target.
CEPC_CaloTiming: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CEPC_CaloTiming
.PHONY : CEPC_CaloTiming

# fast build rule for target.
CEPC_CaloTiming/fast:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/build
.PHONY : CEPC_CaloTiming/fast

#=============================================================================
# Target rules for targets named CEPC_CaloTiming_

# Build rule for target.
CEPC_CaloTiming_: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CEPC_CaloTiming_
.PHONY : CEPC_CaloTiming_

# fast build rule for target.
CEPC_CaloTiming_/fast:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming_.dir/build.make CMakeFiles/CEPC_CaloTiming_.dir/build
.PHONY : CEPC_CaloTiming_/fast

CEPC_CaloTiming.o: CEPC_CaloTiming.cc.o

.PHONY : CEPC_CaloTiming.o

# target to build an object file
CEPC_CaloTiming.cc.o:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/CEPC_CaloTiming.cc.o
.PHONY : CEPC_CaloTiming.cc.o

CEPC_CaloTiming.i: CEPC_CaloTiming.cc.i

.PHONY : CEPC_CaloTiming.i

# target to preprocess a source file
CEPC_CaloTiming.cc.i:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/CEPC_CaloTiming.cc.i
.PHONY : CEPC_CaloTiming.cc.i

CEPC_CaloTiming.s: CEPC_CaloTiming.cc.s

.PHONY : CEPC_CaloTiming.s

# target to generate assembly for a file
CEPC_CaloTiming.cc.s:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/CEPC_CaloTiming.cc.s
.PHONY : CEPC_CaloTiming.cc.s

src/ConfigFile.o: src/ConfigFile.cc.o

.PHONY : src/ConfigFile.o

# target to build an object file
src/ConfigFile.cc.o:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/ConfigFile.cc.o
.PHONY : src/ConfigFile.cc.o

src/ConfigFile.i: src/ConfigFile.cc.i

.PHONY : src/ConfigFile.i

# target to preprocess a source file
src/ConfigFile.cc.i:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/ConfigFile.cc.i
.PHONY : src/ConfigFile.cc.i

src/ConfigFile.s: src/ConfigFile.cc.s

.PHONY : src/ConfigFile.s

# target to generate assembly for a file
src/ConfigFile.cc.s:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/ConfigFile.cc.s
.PHONY : src/ConfigFile.cc.s

src/CreateTree.o: src/CreateTree.cc.o

.PHONY : src/CreateTree.o

# target to build an object file
src/CreateTree.cc.o:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/CreateTree.cc.o
.PHONY : src/CreateTree.cc.o

src/CreateTree.i: src/CreateTree.cc.i

.PHONY : src/CreateTree.i

# target to preprocess a source file
src/CreateTree.cc.i:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/CreateTree.cc.i
.PHONY : src/CreateTree.cc.i

src/CreateTree.s: src/CreateTree.cc.s

.PHONY : src/CreateTree.s

# target to generate assembly for a file
src/CreateTree.cc.s:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/CreateTree.cc.s
.PHONY : src/CreateTree.cc.s

src/DR_PMTHit.o: src/DR_PMTHit.cc.o

.PHONY : src/DR_PMTHit.o

# target to build an object file
src/DR_PMTHit.cc.o:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/DR_PMTHit.cc.o
.PHONY : src/DR_PMTHit.cc.o

src/DR_PMTHit.i: src/DR_PMTHit.cc.i

.PHONY : src/DR_PMTHit.i

# target to preprocess a source file
src/DR_PMTHit.cc.i:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/DR_PMTHit.cc.i
.PHONY : src/DR_PMTHit.cc.i

src/DR_PMTHit.s: src/DR_PMTHit.cc.s

.PHONY : src/DR_PMTHit.s

# target to generate assembly for a file
src/DR_PMTHit.cc.s:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/DR_PMTHit.cc.s
.PHONY : src/DR_PMTHit.cc.s

src/DR_PMTSD.o: src/DR_PMTSD.cc.o

.PHONY : src/DR_PMTSD.o

# target to build an object file
src/DR_PMTSD.cc.o:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/DR_PMTSD.cc.o
.PHONY : src/DR_PMTSD.cc.o

src/DR_PMTSD.i: src/DR_PMTSD.cc.i

.PHONY : src/DR_PMTSD.i

# target to preprocess a source file
src/DR_PMTSD.cc.i:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/DR_PMTSD.cc.i
.PHONY : src/DR_PMTSD.cc.i

src/DR_PMTSD.s: src/DR_PMTSD.cc.s

.PHONY : src/DR_PMTSD.s

# target to generate assembly for a file
src/DR_PMTSD.cc.s:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/DR_PMTSD.cc.s
.PHONY : src/DR_PMTSD.cc.s

src/DetectorConstruction.o: src/DetectorConstruction.cc.o

.PHONY : src/DetectorConstruction.o

# target to build an object file
src/DetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/DetectorConstruction.cc.o
.PHONY : src/DetectorConstruction.cc.o

src/DetectorConstruction.i: src/DetectorConstruction.cc.i

.PHONY : src/DetectorConstruction.i

# target to preprocess a source file
src/DetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/DetectorConstruction.cc.i
.PHONY : src/DetectorConstruction.cc.i

src/DetectorConstruction.s: src/DetectorConstruction.cc.s

.PHONY : src/DetectorConstruction.s

# target to generate assembly for a file
src/DetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/DetectorConstruction.cc.s
.PHONY : src/DetectorConstruction.cc.s

src/EventAction.o: src/EventAction.cc.o

.PHONY : src/EventAction.o

# target to build an object file
src/EventAction.cc.o:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/EventAction.cc.o
.PHONY : src/EventAction.cc.o

src/EventAction.i: src/EventAction.cc.i

.PHONY : src/EventAction.i

# target to preprocess a source file
src/EventAction.cc.i:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/EventAction.cc.i
.PHONY : src/EventAction.cc.i

src/EventAction.s: src/EventAction.cc.s

.PHONY : src/EventAction.s

# target to generate assembly for a file
src/EventAction.cc.s:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/EventAction.cc.s
.PHONY : src/EventAction.cc.s

src/G4EmUserPhysics.o: src/G4EmUserPhysics.cc.o

.PHONY : src/G4EmUserPhysics.o

# target to build an object file
src/G4EmUserPhysics.cc.o:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/G4EmUserPhysics.cc.o
.PHONY : src/G4EmUserPhysics.cc.o

src/G4EmUserPhysics.i: src/G4EmUserPhysics.cc.i

.PHONY : src/G4EmUserPhysics.i

# target to preprocess a source file
src/G4EmUserPhysics.cc.i:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/G4EmUserPhysics.cc.i
.PHONY : src/G4EmUserPhysics.cc.i

src/G4EmUserPhysics.s: src/G4EmUserPhysics.cc.s

.PHONY : src/G4EmUserPhysics.s

# target to generate assembly for a file
src/G4EmUserPhysics.cc.s:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/G4EmUserPhysics.cc.s
.PHONY : src/G4EmUserPhysics.cc.s

src/LedFiberTiming.o: src/LedFiberTiming.cc.o

.PHONY : src/LedFiberTiming.o

# target to build an object file
src/LedFiberTiming.cc.o:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/LedFiberTiming.cc.o
.PHONY : src/LedFiberTiming.cc.o

src/LedFiberTiming.i: src/LedFiberTiming.cc.i

.PHONY : src/LedFiberTiming.i

# target to preprocess a source file
src/LedFiberTiming.cc.i:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/LedFiberTiming.cc.i
.PHONY : src/LedFiberTiming.cc.i

src/LedFiberTiming.s: src/LedFiberTiming.cc.s

.PHONY : src/LedFiberTiming.s

# target to generate assembly for a file
src/LedFiberTiming.cc.s:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/LedFiberTiming.cc.s
.PHONY : src/LedFiberTiming.cc.s

src/MyMaterials.o: src/MyMaterials.cc.o

.PHONY : src/MyMaterials.o

# target to build an object file
src/MyMaterials.cc.o:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/MyMaterials.cc.o
.PHONY : src/MyMaterials.cc.o

src/MyMaterials.i: src/MyMaterials.cc.i

.PHONY : src/MyMaterials.i

# target to preprocess a source file
src/MyMaterials.cc.i:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/MyMaterials.cc.i
.PHONY : src/MyMaterials.cc.i

src/MyMaterials.s: src/MyMaterials.cc.s

.PHONY : src/MyMaterials.s

# target to generate assembly for a file
src/MyMaterials.cc.s:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/MyMaterials.cc.s
.PHONY : src/MyMaterials.cc.s

src/PrimaryGeneratorAction.o: src/PrimaryGeneratorAction.cc.o

.PHONY : src/PrimaryGeneratorAction.o

# target to build an object file
src/PrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/PrimaryGeneratorAction.cc.o
.PHONY : src/PrimaryGeneratorAction.cc.o

src/PrimaryGeneratorAction.i: src/PrimaryGeneratorAction.cc.i

.PHONY : src/PrimaryGeneratorAction.i

# target to preprocess a source file
src/PrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/PrimaryGeneratorAction.cc.i
.PHONY : src/PrimaryGeneratorAction.cc.i

src/PrimaryGeneratorAction.s: src/PrimaryGeneratorAction.cc.s

.PHONY : src/PrimaryGeneratorAction.s

# target to generate assembly for a file
src/PrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/PrimaryGeneratorAction.cc.s
.PHONY : src/PrimaryGeneratorAction.cc.s

src/RunAction.o: src/RunAction.cc.o

.PHONY : src/RunAction.o

# target to build an object file
src/RunAction.cc.o:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/RunAction.cc.o
.PHONY : src/RunAction.cc.o

src/RunAction.i: src/RunAction.cc.i

.PHONY : src/RunAction.i

# target to preprocess a source file
src/RunAction.cc.i:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/RunAction.cc.i
.PHONY : src/RunAction.cc.i

src/RunAction.s: src/RunAction.cc.s

.PHONY : src/RunAction.s

# target to generate assembly for a file
src/RunAction.cc.s:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/RunAction.cc.s
.PHONY : src/RunAction.cc.s

src/SteppingAction.o: src/SteppingAction.cc.o

.PHONY : src/SteppingAction.o

# target to build an object file
src/SteppingAction.cc.o:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/SteppingAction.cc.o
.PHONY : src/SteppingAction.cc.o

src/SteppingAction.i: src/SteppingAction.cc.i

.PHONY : src/SteppingAction.i

# target to preprocess a source file
src/SteppingAction.cc.i:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/SteppingAction.cc.i
.PHONY : src/SteppingAction.cc.i

src/SteppingAction.s: src/SteppingAction.cc.s

.PHONY : src/SteppingAction.s

# target to generate assembly for a file
src/SteppingAction.cc.s:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/SteppingAction.cc.s
.PHONY : src/SteppingAction.cc.s

src/SteppingVerbose.o: src/SteppingVerbose.cc.o

.PHONY : src/SteppingVerbose.o

# target to build an object file
src/SteppingVerbose.cc.o:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/SteppingVerbose.cc.o
.PHONY : src/SteppingVerbose.cc.o

src/SteppingVerbose.i: src/SteppingVerbose.cc.i

.PHONY : src/SteppingVerbose.i

# target to preprocess a source file
src/SteppingVerbose.cc.i:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/SteppingVerbose.cc.i
.PHONY : src/SteppingVerbose.cc.i

src/SteppingVerbose.s: src/SteppingVerbose.cc.s

.PHONY : src/SteppingVerbose.s

# target to generate assembly for a file
src/SteppingVerbose.cc.s:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/SteppingVerbose.cc.s
.PHONY : src/SteppingVerbose.cc.s

src/SurfaceProperty.o: src/SurfaceProperty.cc.o

.PHONY : src/SurfaceProperty.o

# target to build an object file
src/SurfaceProperty.cc.o:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/SurfaceProperty.cc.o
.PHONY : src/SurfaceProperty.cc.o

src/SurfaceProperty.i: src/SurfaceProperty.cc.i

.PHONY : src/SurfaceProperty.i

# target to preprocess a source file
src/SurfaceProperty.cc.i:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/SurfaceProperty.cc.i
.PHONY : src/SurfaceProperty.cc.i

src/SurfaceProperty.s: src/SurfaceProperty.cc.s

.PHONY : src/SurfaceProperty.s

# target to generate assembly for a file
src/SurfaceProperty.cc.s:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/SurfaceProperty.cc.s
.PHONY : src/SurfaceProperty.cc.s

src/TrackInformation.o: src/TrackInformation.cc.o

.PHONY : src/TrackInformation.o

# target to build an object file
src/TrackInformation.cc.o:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/TrackInformation.cc.o
.PHONY : src/TrackInformation.cc.o

src/TrackInformation.i: src/TrackInformation.cc.i

.PHONY : src/TrackInformation.i

# target to preprocess a source file
src/TrackInformation.cc.i:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/TrackInformation.cc.i
.PHONY : src/TrackInformation.cc.i

src/TrackInformation.s: src/TrackInformation.cc.s

.PHONY : src/TrackInformation.s

# target to generate assembly for a file
src/TrackInformation.cc.s:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/TrackInformation.cc.s
.PHONY : src/TrackInformation.cc.s

src/TrackingAction.o: src/TrackingAction.cc.o

.PHONY : src/TrackingAction.o

# target to build an object file
src/TrackingAction.cc.o:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/TrackingAction.cc.o
.PHONY : src/TrackingAction.cc.o

src/TrackingAction.i: src/TrackingAction.cc.i

.PHONY : src/TrackingAction.i

# target to preprocess a source file
src/TrackingAction.cc.i:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/TrackingAction.cc.i
.PHONY : src/TrackingAction.cc.i

src/TrackingAction.s: src/TrackingAction.cc.s

.PHONY : src/TrackingAction.s

# target to generate assembly for a file
src/TrackingAction.cc.s:
	$(MAKE) -f CMakeFiles/CEPC_CaloTiming.dir/build.make CMakeFiles/CEPC_CaloTiming.dir/src/TrackingAction.cc.s
.PHONY : src/TrackingAction.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... edit_cache"
	@echo "... CEPC_CaloTiming"
	@echo "... CEPC_CaloTiming_"
	@echo "... rebuild_cache"
	@echo "... CEPC_CaloTiming.o"
	@echo "... CEPC_CaloTiming.i"
	@echo "... CEPC_CaloTiming.s"
	@echo "... src/ConfigFile.o"
	@echo "... src/ConfigFile.i"
	@echo "... src/ConfigFile.s"
	@echo "... src/CreateTree.o"
	@echo "... src/CreateTree.i"
	@echo "... src/CreateTree.s"
	@echo "... src/DR_PMTHit.o"
	@echo "... src/DR_PMTHit.i"
	@echo "... src/DR_PMTHit.s"
	@echo "... src/DR_PMTSD.o"
	@echo "... src/DR_PMTSD.i"
	@echo "... src/DR_PMTSD.s"
	@echo "... src/DetectorConstruction.o"
	@echo "... src/DetectorConstruction.i"
	@echo "... src/DetectorConstruction.s"
	@echo "... src/EventAction.o"
	@echo "... src/EventAction.i"
	@echo "... src/EventAction.s"
	@echo "... src/G4EmUserPhysics.o"
	@echo "... src/G4EmUserPhysics.i"
	@echo "... src/G4EmUserPhysics.s"
	@echo "... src/LedFiberTiming.o"
	@echo "... src/LedFiberTiming.i"
	@echo "... src/LedFiberTiming.s"
	@echo "... src/MyMaterials.o"
	@echo "... src/MyMaterials.i"
	@echo "... src/MyMaterials.s"
	@echo "... src/PrimaryGeneratorAction.o"
	@echo "... src/PrimaryGeneratorAction.i"
	@echo "... src/PrimaryGeneratorAction.s"
	@echo "... src/RunAction.o"
	@echo "... src/RunAction.i"
	@echo "... src/RunAction.s"
	@echo "... src/SteppingAction.o"
	@echo "... src/SteppingAction.i"
	@echo "... src/SteppingAction.s"
	@echo "... src/SteppingVerbose.o"
	@echo "... src/SteppingVerbose.i"
	@echo "... src/SteppingVerbose.s"
	@echo "... src/SurfaceProperty.o"
	@echo "... src/SurfaceProperty.i"
	@echo "... src/SurfaceProperty.s"
	@echo "... src/TrackInformation.o"
	@echo "... src/TrackInformation.i"
	@echo "... src/TrackInformation.s"
	@echo "... src/TrackingAction.o"
	@echo "... src/TrackingAction.i"
	@echo "... src/TrackingAction.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

